window.WC_GRID_ITEMS = [
  {
    label: 'Dinner tonight',
    title: 'Takeout again',
    stat: 'You opened the delivery app before you opened the fridge.',
    hoverTitle: 'Asian cuisine',
    hoverStat: "Order something you can't pronounce.",
    icon: 'img/categories/dinner.webp',
    desktop: { colFrac: 0.09, row: 3, w: 4, h: 4 },
    mobile: { colFrac: 0, row: 3, w: 4, h: 4 },
  },
  {
    label: 'Coffee shop',
    title: 'The usual',
    stat: "Didn't even check what's new — just ordered the usual.",
    hoverTitle: "Barista's choice",
    hoverStat: 'Ask them to surprise you.',
    icon: 'img/categories/coffeeshop.webp',
    desktop: { colFrac: 0.82, row: 8, w: 4, h: 4 },
    mobile: { colFrac: 1, row: 8, w: 4, h: 4 },
  },
  {
    label: 'Restaurant order',
    title: 'Same order',
    stat: "You didn't open the menu.",
    hoverTitle: 'First impression',
    hoverStat: 'Order the first thing your eyes landed on.',
    icon: 'img/categories/restaurant.webp',
    desktop: { colFrac: 0.27, row: 13, w: 4, h: 4 },
    mobile: { colFrac: 0, row: 13, w: 4, h: 4 },
  },
  {
    label: 'Workout',
    title: 'Leg day',
    stat: 'The one you always reschedule.',
    hoverTitle: 'Walk double the usual',
    hoverStat: 'Twice your normal route.',
    icon: 'img/categories/workout.webp',
    desktop: { colFrac: 0.91, row: 18, w: 4, h: 4 },
    mobile: { colFrac: 1, row: 18, w: 4, h: 4 },
  },
  {
    label: 'Screen time',
    title: 'Comfort rewatch',
    stat: 'Watching whatever your feed suggests.',
    hoverTitle: 'Guilty pleasure',
    hoverStat: "Reality TV you're embarrassed to admit.",
    icon: 'img/categories/screentime.webp',
    desktop: { colFrac: 0.09, row: 23, w: 4, h: 4 },
    mobile: { colFrac: 0, row: 23, w: 4, h: 4 },
  },
  {
    label: 'Friday night',
    title: 'Same plans',
    stat: 'Same answer you gave last Friday.',
    hoverTitle: 'New neighborhood',
    hoverStat: 'A part of town you never visit.',
    icon: 'img/categories/weekend.webp',
    desktop: { colFrac: 0.73, row: 28, w: 4, h: 4 },
    mobile: { colFrac: 1, row: 28, w: 4, h: 4 },
  },
  {
    label: 'Reach out',
    title: 'They text first',
    stat: "You're always just replying.",
    hoverTitle: 'Out of the blue',
    hoverStat: "Text someone who isn't expecting it.",
    icon: 'img/categories/reachout.webp',
    desktop: { colFrac: 0.36, row: 33, w: 4, h: 4 },
    mobile: { colFrac: 0, row: 33, w: 4, h: 4 },
  },
  {
    label: 'Wind down',
    title: 'Phone in bed',
    stat: 'Meant to sleep. Still scrolling.',
    hoverTitle: 'Tea ritual',
    hoverStat: 'Make a hot drink. Finish it screen-free.',
    icon: 'img/categories/winddown.webp',
    desktop: { colFrac: 0.91, row: 38, w: 4, h: 4 },
    mobile: { colFrac: 1, row: 38, w: 4, h: 4 },
  },
];
